services:
  web:
    container_name: quanda-web
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=quanda
      - FLASK_DEBUG=true
      - HOST=0.0.0.0  # IMPORTANT: Make Flask listen on all interfaces
      - SECRET_KEY=${SECRET_KEY:-dev_key_change_in_production}
      - LOG_LEVEL=INFO
      # Wait for database to start before starting app
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - quanda-network
    restart: unless-stopped

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quanda
    ports:
      - "5432:5432"
    networks:
      - quanda-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  quanda-network:
    driver: bridge

volumes:
  postgres_data: